---
- hosts: all
  vars_files:
    - ../env_variables
  tasks:
    - name: Creating a kubernetes repo
      file: 
        path: /etc/yum/repos.d/kubernetes.repo
        state: touch
    - name: Adding repository details
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
          https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    - name: Installing required packages
      yum:
        name: "{{ element }}"
        state: present
      loop: "{{ packages }}"
      loop_control:
        loop_var: element 
    - name: Start and enable the packages
      service:
        name: "{{ element }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      loop_control:
        loop_var: element
    - name: Allow network ports in firewalld
      firewalld:
        name: "{{ element }}"
        state: enabled
        permanent: yes
        immediate: yes
      loop: "{{ ports }}"
      loop_control:
        loop_var: element
    - name: Enabling Bridge Firewall Rule
     shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"      
